version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: casadocodigo
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: